version: "3.10"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "${Django_PORT}:${Django_PORT}"
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT_LOCAL}:${PGADMIN_PORT_CONTAINER}"
    env_file:
      - .env-pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "my-rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "rabbitmq"
    ports:
      - "5673:5672"
      - "15673:15672"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A django_profiles worker -l info
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data:
  pgadmin_data:
